# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_KEY_CONTENT"],
      is_key_content_base64: true
    )

    build_app(
      workspace: "PageHub.xcworkspace",
      scheme: "PageHub",
      xcargs: "SWIFT_ENABLE_MACROS=YES",
      destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
           "com.pagehub.app" => "match AppStore com.pagehub.app"
         }
      }
    )

    upload_to_testflight

  end

  lane :development do
    api_key = app_store_connect_api_key(
      key_id: "77PMCWA243",
      issuer_id: "2e63d6a0-0311-4457-8fbf-d8d17836a8aa",
      key_filepath: "77PMCWA243.p8"
    )

    match(
      type: "development",
      app_identifier: ["com.pagehub.app"],
      api_key: api_key
    )
  end

  lane :appstore do 
    api_key = app_store_connect_api_key(
      key_id: "77PMCWA243",
      issuer_id: "2e63d6a0-0311-4457-8fbf-d8d17836a8aa",
      key_filepath: "77PMCWA243.p8"
    )

    match(
      type: "appstore",
      app_identifier: ["com.pagehub.app"],
      api_key: api_key
    )
  end
end
