# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Google Cloud Setup

on:
  push:
    branches:
      - 'chore/**'  # chore/ 하위 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Create Google Cloud Key File
      run: |
        echo "${{ secrets.PAGEHUB_SERVICE }}" | base64 --decode > /tmp/service-account-key.json
    
    - name: Install Google Cloud CLI SDK
      run: |
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-darwin-x86_64.tar.gz
        tar -xf google-cloud-cli-darwin-x86_64.tar.gz
        ./google-cloud-sdk/install.sh
        cat /tmp/service-account-key.json
        ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
        
    - name: Install Firebase CLI SDK
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        curl -sL https://firebase.tools | bash
        
        # Firestore 사용 설정
        firebase deploy --only firestore
