# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Google Cloud Setup

on:
  push:
    branches:
      - 'chore/**'  # chore/ 하위 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Google Cloud Key File
      run: |
        echo "${{ secrets.PAGEHUB_SERVICE }}" | base64 --decode > /tmp/service-account-key.json
    
    - name: Install Google Cloud CLI SDK
      run: |
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-darwin-x86_64.tar.gz
        tar -xf google-cloud-cli-darwin-x86_64.tar.gz
        ./google-cloud-sdk/install.sh
        cat /tmp/service-account-key.json
        
        # 환경 변수 PATH에 Google Cloud SDK 경로 추가
        echo "$(pwd)/google-cloud-sdk/bin" >> $GITHUB_PATH
        
        ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
        
    - name: Install Firebase CLI SDK
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY}}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        echo "$FIREBASE_SERVICE_KEY" | base64 --decode > /tmp/firebase-key.json 
        curl -sL https://firebase.tools | bash
        
        # 로그인 확인. 실행안될 경우 Firebase token 확인, *firebase login:ci
        firebase projects:list
        
        firebase deploy --only firestore
        
        # API 호출 확인
        curl -X GET \
        "https://firestore.googleapis.com/v1/projects/$FIREBASE_PROJECT_ID/databases/(default)/documents/FeatureCode/code111" \
        -H "Authorization: Bearer $(./google-cloud-sdk/bin/gcloud auth print-access-token)"
        
    - name: Update Firestore with Modified Snippets
      env:
        SNIPPET_COLLECTION: ${{ secrets.SWIFTUI_SNIPPET_COLLECTION }}
        FIRESTORE_CODEDETAILS_DOCUMENT: ${{ secrets.FIRESTORE_CODEDETAILS_DOCUMENT }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        git fetch origin main
        
        # 버전 형식을 다음처럼 추출합니다. "18.0.0"
        MIN_IOS_VERSION=$(grep -o '.iOS(.*)' Project.swift | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
        echo "MIN IOS VERSION: $MIN_IOS_VERSION"
        
        # Snippet 하위의 변경된 파일들만 확인
        CHANGED_FILES=$(git diff --name-only origin/main $GITHUB_SHA | grep "^PageHub/Sources/Snippet")
        echo "Changed files: $CHANGED_FILES"

        # 변경된 파일 모두 찾아가서 내부 코드를 출력하며, //로 시작하는 주석 제거
        for FILE in $CHANGED_FILES; do
          if [ -f "$FILE" ]; then
            echo "Contents of $FILE without comments:"

            # 마지막 슬래시(/) 이전까지의 경로를 추출하고, 첫 글자를 소문자로 변환
            DOCUMENT=$(echo "$FILE" | sed -E 's|.*/||; s|\.swift$||' | awk '{print tolower(substr($0,1,1)) substr($0,2)}')
            echo "document name is $DOCUMENT"

            # 변경된 파일에서 주석 처리된 라인 제거 후 환경변수에 저장
            CODE=$(sed '/^\/\//d' "$FILE")

            # GET 및 PATCH 요청에 사용하는 URL
            FIRESTORE_READ_UPDATE_URL="https://firestore.googleapis.com/v1/projects/$FIREBASE_PROJECT_ID/databases/(default)/documents/$SNIPPET_COLLECTION/$DOCUMENT/$MIN_IOS_VERSION/$FIRESTORE_CODEDETAILS_DOCUMENT"

            # POST 요청에 사용하는 URL
            FIRESTORE_CREATE_URL="https://firestore.googleapis.com/v1/projects/$FIREBASE_PROJECT_ID/databases/(default)/documents/$SNIPPET_COLLECTION/$DOCUMENT/$MIN_IOS_VERSION?documentId=$FIRESTORE_CODEDETAILS_DOCUMENT"

            # Firestore에서 문서가 존재하는지 확인
            RESPONSE=$(curl -s \
              -o /dev/null \
              -w "%{http_code}" \
              -H "Authorization: Bearer $(./google-cloud-sdk/bin/gcloud auth print-access-token)"\
              "$FIRESTORE_READ_UPDATE_URL")

            echo "응답: $RESPONSE"

            if [ "$RESPONSE" -eq 200 ]; then
              # 문서가 존재하면 PATCH 요청
              curl -X PATCH \
              -H "Authorization: Bearer $(./google-cloud-sdk/bin/gcloud auth print-access-token)"\
              -H "Content-Type: application/json" \
              "$FIRESTORE_READ_UPDATE_URL" \
              -d '{
                "fields": {
                  "code": {
                    "stringValue": "'"${CODE}"'"
                  }
                }
              }'

              echo "Document updated with PATCH."

            else
              # 문서가 존재하지 않으면 POST 요청
              curl -X POST \
              -H "Authorization: Bearer $(./google-cloud-sdk/bin/gcloud auth print-access-token)"\
              -H "Content-Type: application/json" \
              "$FIRESTORE_CREATE_URL" \
              -d '{
                "fields": {
                  "code": {
                    "stringValue": "'"${CODE}"'"
                  }
                }
              }'

              echo "Document created with POST."
            fi
          else

          echo "File $FILE does not exist."

        fi
        done

