name: Update Modified Codes

on:
  pull_request:
    types:
      - opened 
      - synchronize

jobs:
  build:
    runs-on: macOS-15
    env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        
        FIRESTORE_TEST_SNIPPETS_COLLECTION: ${{ secrets.FIRESTORE_TEST_SNIPPETS_COLLECTION }}
        FIRESTORE_TEST_FEATURES_COLLECTION: ${{ secrets.FIRESTORE_TEST_FEATURES_COLLECTION }}

        FIRESTORE_PRODUCT_SNIPPETS_COLLECTION: ${{ secrets.FIRESTORE_PRODUCT_SNIPPETS_COLLECTION }}

        FIRESTORE_CODEDETAILS_DOCUMENT: ${{ secrets.FIRESTORE_CODEDETAILS_DOCUMENT }}
        FIRESTORE_SNIPPETS_DOCUMENT: ${{ secrets.FIRESTORE_SNIPPETS_DOCUMENT }}
        FIRESTORE_SUBSNIPPETS_DOCUMENT: ${{ secrets.FIRESTORE_SUBSNIPPETS_DOCUMENT }}


    steps:
    - uses: actions/checkout@v4

    - name: Check for the existence of modified files
      run: |
        CHANGED_FILES=$(git diff --name-only origin/main $GITHUB_SHA | grep "^PageHub/Sources/Snippet" || true)

        if [ -n "$CHANGED_FILES" ]; then 
          echo "No modified files detected in PageHub/Sources/Snippet. Exiting"
          exit 0
        fi
 
    
    - name: Install required SDKs
      uses: ./.github/actions/install-sdk
      with:
        GOOGLE_CLOUD_SERVICE_KEY: ${{ secrets.PAGEHUB_SERVICE }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}

    - name: Set Up Environment Variables
      run: |
        git fetch origin main

        # Extract the line containing '.iOS(...)' from Project.swift
        # Example output: .iOS("18.0")
        IOS_LINE=$(grep -o '.iOS(.*)' PageHub/Project.swift)


        # Extract the version number in the format 'number.number' from the line
        # Example input: .iOS("18.0"), output: 18.0
        MIN_IOS_VERSION=$(echo "$IOS_LINE" | grep -o '[0-9]\+\.[0-9]\+')

        echo "MIN_IOS_VERSION=$MIN_IOS_VERSION" >> $GITHUB_ENV
        
        # Github actions에서는 Bash 스타일 변수를 with에 사용할 수 없다.
        # $ {{ }} 문법 형태를 사용해야해서, env에 저장 후 사용한다. 
        echo "$CHANGED_FILES"
        echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
        echo "$CHANGED_FILES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
        ACCESS_TOKEN=$(./google-cloud-sdk/bin/gcloud auth print-access-token)
        echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
        
        echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> $GITHUB_ENV
        echo "FIRESTORE_TEST_SNIPPETS_COLLECTION=$FIRESTORE_TEST_SNIPPETS_COLLECTION" >> $GITHUB_ENV
        echo "FIRESTORE_CODEDETAILS_DOCUMENT=$FIRESTORE_CODEDETAILS_DOCUMENT" >> $GITHUB_ENV

        echo "FIRESTORE_TEST_FEATURES_COLLECTION=$FIRESTORE_TEST_FEATURES_COLLECTION" >> $GITHUB_ENV
        echo "FIRESTORE_SNIPPETS_DOCUMENT=$FIRESTORE_SNIPPETS_DOCUMENT" >> $GITHUB_ENV

    - name: Update Snippet Codes
      uses: ./.github/actions/upload-snippets-to-firestore
      with:
        FILES: ${{ env.CHANGED_FILES }}

    - name: Set Up Environment Values for Check Snippet Code
      run: |
        echo "FIRESTORE_SNIPPETS_COLLECTION=$FIRESTORE_TEST_SNIPPETS_COLLECTION" >> $GITHUB_ENV
        echo "FIRESTORE_CODEDETAILS_DOCUMENT=$FIRESTORE_CODEDETAILS_DOCUMENT" >> $GITHUB_ENV
        echo "FIRESTORE_SUBSNIPPETS_DOCUMENT=$FIRESTORE_SUBSNIPPETS_DOCUMENT" >> $GITHUB_ENV

    - name: Check Snippet Code
      uses: ./.github/actions/check-snippet-code
      with: 
        FILES: ${{ env.CHANGED_FILES }}
    
      
