# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Update all Snippet to Test Database

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        
        FIRESTORE_TEST_SNIPPETS_COLLECTION: ${{ secrets.FIRESTORE_TEST_SNIPPETS_COLLECTION }}
        FIRESTORE_CODEDETAILS_DOCUMENT: ${{ secrets.FIRESTORE_CODEDETAILS_DOCUMENT }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required SDKs
      uses: ./.github/actions/install-sdk
      with:
        GOOGLE_CLOUD_SERVICE_KEY: ${{ secrets.PAGEHUB_SERVICE }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}

    - name: Configure
      run: |
        git fetch origin main
        
        MIN_IOS_VERSION=$(grep -o '.iOS(.*)' Project.swift | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
        echo "MIN_IOS_VERSION=$MIN_IOS_VERSION" >> $GITHUB_ENV

        CHANGED_FILES=$(find PageHub/Sources/Snippet -type f)
        
        # Github actions에서는 Bash 스타일 변수를 with에 사용할 수 없다.
        # $ {{ }} 문법 형태를 사용해야해서, env에 저장 후 사용한다. 
        echo "$CHANGED_FILES"
        echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
        echo "$CHANGED_FILES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
        ACCESS_TOKEN=$(./google-cloud-sdk/bin/gcloud auth print-access-token)
        echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
        
        echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> $GITHUB_ENV
        echo "FIRESTORE_TEST_SNIPPETS_COLLECTION=$FIRESTORE_TEST_SNIPPETS_COLLECTION" >> $GITHUB_ENV
        echo "FIRESTORE_CODEDETAILS_DOCUMENT=$FIRESTORE_CODEDETAILS_DOCUMENT" >> $GITHUB_ENV

    - name: Call 
      uses: ./.github/actions/upload-to-firestore
      with:
        FILES: ${{ env.CHANGED_FILES }}
