# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Google Cloud Setup

on:
  push:
    branches:
      - 'chore/**'  # chore/ 하위 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: macos-latest
    env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        
        FIRESTORE_TEST_SNIPPETS_COLLECTION: ${{ secrets.FIRESTORE_TEST_SNIPPETS_COLLECTION }}
        FIRESTORE_TEST_FEATURES_COLLECTION: ${{ secrets.FIRESTORE_TEST_FEATURES_COLLECTION }}

        FIRESTORE_CODEDETAILS_DOCUMENT: ${{ secrets.FIRESTORE_CODEDETAILS_DOCUMENT }}
        FIRESTORE_SNIPPETS_DOCUMENT: ${{ secrets.FIRESTORE_SNIPPETS_DOCUMENT }}
        FIRESTORE_SUBSNIPPETS_DOCUMENT: ${{ secrets.FIRESTORE_SUBSNIPPETS_DOCUMENT }}


    steps:
    - uses: actions/checkout@v4
    
    - name: Install required SDKs
      uses: ./.github/actions/install-sdk
      with:
        GOOGLE_CLOUD_SERVICE_KEY: ${{ secrets.PAGEHUB_SERVICE }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}

    - name: Set Up Environment Variables
      run: |
        git fetch origin main
        MIN_IOS_VERSION=$(grep -o '.iOS(.*)' Project.swift | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
        echo "MIN_IOS_VERSION=$MIN_IOS_VERSION" >> $GITHUB_ENV

        CHANGED_FILES=$(git diff --name-only origin/main $GITHUB_SHA | grep "^PageHub/Sources/Snippet" || true)

        if [ -z "$CHANGED_FILES" ]; then
          echo "No changes detected in PageHub/Sources/Snippet."
        else
          echo "Changed files: $CHANGED_FILES"
        # 여기서 추가 작업 실행
        fi
        
        # Github actions에서는 Bash 스타일 변수를 with에 사용할 수 없다.
        # $ {{ }} 문법 형태를 사용해야해서, env에 저장 후 사용한다. 
        echo "$CHANGED_FILES"
        echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
        echo "$CHANGED_FILES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
        ACCESS_TOKEN=$(./google-cloud-sdk/bin/gcloud auth print-access-token)
        echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
        
        echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> $GITHUB_ENV
        echo "FIRESTORE_TEST_SNIPPETS_COLLECTION=$FIRESTORE_TEST_SNIPPETS_COLLECTION" >> $GITHUB_ENV
        echo "FIRESTORE_CODEDETAILS_DOCUMENT=$FIRESTORE_CODEDETAILS_DOCUMENT" >> $GITHUB_ENV

        echo "FIRESTORE_TEST_FEATURES_COLLECTION=$FIRESTORE_TEST_FEATURES_COLLECTION" >> $GITHUB_ENV
        echo "FIRESTORE_SNIPPETS_DOCUMENT=$FIRESTORE_SNIPPETS_DOCUMENT" >> $GITHUB_ENV
        
        # 변경된 FEATURE 정보를 저장합니다.
        FEATURE_MAPPING_FILES=$(git diff --name-only origin/main $GITHUB_SHA | grep "^PageHub/Resources/FeatureSnippetMap" || true)
        
        if [ -z "$FEATURE_MAPPING_FILES"; then 
          echo "No changes detected in PageHub/Resources/FeatureSnippetMap."
        else 
          echo "Changed feature map: $FEATURE_MAPPING_FILES"
          echo "FEATURE_MAPPING_FILES<<EOF" >> $GITHUB_ENV
          echo "$FEATURE_MAPPING_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        fi

    - name: Call 
      uses: ./.github/actions/upload-snippets-to-firestore
      with:
        FILES: ${{ env.CHANGED_FILES }}

    - name: Update Firestore with Features
      uses: ./.github/actions/update-features-to-firestore

    - name: Set Up Environment Values for Update Subsnippet
      run: |
        echo "FIRESTORE_SNIPPETS_COLLECTION=$FIRESTORE_TEST_SNIPPETS_COLLECTION" >> $GITHUB_ENV
        SUBSNIPPET_MAP_FILES=$(git diff --name-only origin/main $GITHUB_SHA | grep "^PageHub/Resources/SubsnippetMap" || true)

        echo "FIRESTORE_SUBSNIPPETS_DOCUMENT=$FIRESTORE_SUBSNIPPETS_DOCUMENT" >> $GITHUB_ENV

        if [ -z "$SUBSNIPPET_MAP_FILES" ]; then 
          echo "No changes detected in PageHub/Resources/SubsnippetMap."
        else 
          echo "Changed feature map: $SUBSNIPPET_MAP_FILES"
          echo "SUBSNIPPET_MAP_FILES<<EOF" >> $GITHUB_ENV
          echo "$SUBSNIPPET_MAP_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        fi


    - name: Update Subsnippet
      uses: ./.github/actions/update-subsnippets-to-firestore
      
