# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Update Feature

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        
        FIRESTORE_CODEDETAILS_DOCUMENT: ${{ secrets.FIRESTORE_CODEDETAILS_DOCUMENT }}
        FIRESTORE_SNIPPETS_DOCUMENT: ${{ secrets.FIRESTORE_SNIPPETS_DOCUMENT }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required SDKs
      uses: ./.github/actions/install-sdk
      with:
        GOOGLE_CLOUD_SERVICE_KEY: ${{ secrets.PAGEHUB_SERVICE }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}

    - name: Set Up Environment Values
        echo "FIRESTORE_TEST_FEATURES_COLLECTION=$FIRESTORE_TEST_FEATURES_COLLECTION" >> $GITHUB_ENV
        echo "FIRESTORE_SNIPPETS_DOCUMENT=$FIRESTORE_SNIPPETS_DOCUMENT" >> $GITHUB_ENV

    - name: Call 
      uses: ./.github/actions/update-features-to-firestore
