name: Update Designated Snippet`s Version List

on:
  workflow_dispatch:
    inputs:
      SNIPPETS_INPUT:
        Description: 'The snippet name is saved as a document in the database. Be careful with case sensitivity. Multiple snippets can be included by separating them with \n.'
        required: true
      NEW_VERSION:
        description: 'The iOS version to be added'
        required: true
      COLLECTION_TARGET:
        description: 'Choose between Test and Product for the target collection'
        required: true

jobs:
  build:
    runs-on: macos-15
    env:
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required SDKs
      uses: ./.github/actions/install-sdk
      with:
        GOOGLE_CLOUD_SERVICE_KEY: ${{ secrets.PAGEHUB_SERVICE }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}

    - name: Set Up Environment Variables to Update Snippets 
      run: |
        ACCESS_TOKEN=$(./google-cloud-sdk/bin/gcloud auth print-access-token)
        echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
        
        echo "NEW_VERSION=${{ github.event.inputs.NEW_VERSION }}" >> $GITHUB_ENV
        echo "SNIPPETS_INPUT=${{ github.event.inputs.SNIPPETS_INPUT }}" >> $GITHUB_ENV
        echo "COLLECTION_TARGET=${{ github.event.inputs.COLLECTION_TARGET }}" >> $GITHUB_ENV
        
        echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> $GITHUB_ENV

    - name: Add Version
      uses: ./.github/actions/add-version-to-firestore
