# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Google Cloud Setup

on:
  push:
    branches:
      - 'chore/**'  # chore/ 하위 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: macos-latest
    env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        
        FIRESTORE_TEST_SNIPPETS_COLLECTION: ${{ secrets.FIRESTORE_TEST_SNIPPETS_COLLECTION }}
        FIRESTORE_TEST_FEATURES_COLLECTION: ${{ secrets.FIRESTORE_TEST_FEATURES_COLLECTION }}

        FIRESTORE_CODEDETAILS_DOCUMENT: ${{ secrets.FIRESTORE_CODEDETAILS_DOCUMENT }}
        FIRESTORE_SNIPPETS_DOCUMENT: ${{ secrets.FIRESTORE_SNIPPETS_DOCUMENT }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required SDKs
      uses: ./.github/actions/install-sdk
      with:
        GOOGLE_CLOUD_SERVICE_KEY: ${{ secrets.PAGEHUB_SERVICE }}
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}

    - name: Set Up Environment Variables
      run: |
        git fetch origin main
        MIN_IOS_VERSION=$(grep -o '.iOS(.*)' Project.swift | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
        echo "MIN_IOS_VERSION=$MIN_IOS_VERSION" >> $GITHUB_ENV

        CHANGED_FILES=$(git diff --name-only origin/main $GITHUB_SHA | grep "^PageHub/Sources/Snippet" || true)

        if [ -z "$CHANGED_FILES" ]; then
          echo "No changes detected in PageHub/Sources/Snippet."
        else
          echo "Changed files: $CHANGED_FILES"
        # 여기서 추가 작업 실행
        fi
        
        # Github actions에서는 Bash 스타일 변수를 with에 사용할 수 없다.
        # $ {{ }} 문법 형태를 사용해야해서, env에 저장 후 사용한다. 
        echo "$CHANGED_FILES"
        echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
        echo "$CHANGED_FILES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
        ACCESS_TOKEN=$(./google-cloud-sdk/bin/gcloud auth print-access-token)
        echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
        
        echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> $GITHUB_ENV
        echo "FIRESTORE_TEST_SNIPPETS_COLLECTION=$FIRESTORE_TEST_SNIPPETS_COLLECTION" >> $GITHUB_ENV
        echo "FIRESTORE_CODEDETAILS_DOCUMENT=$FIRESTORE_CODEDETAILS_DOCUMENT" >> $GITHUB_ENV

    - name: Call 
      uses: ./.github/actions/upload-to-firestore
      with:
        FILES: ${{ env.CHANGED_FILES }}

    - name: Update Firestore with Features
      run: |
        jq -r 'to_entries[] | "\(.key) \(.value | @json)"' PageHub/Resources/feature_snippets_mapping.json | while read -r KEY ARRAY_JSON; do
        # KEY의 첫 글자를 소문자로 변환하여 FEATURE_KEY에 할당

        FEATURE_KEY=$(echo "$KEY" | awk '{print tolower(substr($0,1,1)) substr($0,2)}')
        export FEATURE_KEY  # FEATURE_KEY 환경 변수로 설정
        echo "Key: $FEATURE_KEY"
        echo "Value: $ARRAY_JSON"

        # URL 구성
        URL="https://firestore.googleapis.com/v1/projects/$FIREBASE_PROJECT_ID/databases/(default)/documents/$FIRESTORE_TEST_FEATURES_COLLECTION/$FEATURE_KEY/$MIN_IOS_VERSION?documentId=$FIRESTORE_SNIPPETS_DOCUMENT"
        echo "URL: $URL"

          # Firestore에 배열 업로드
          curl -X POST \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            "$URL" \
            -d '{
            "fields": {
              "arrayField": {
                "arrayValue": {
                  "values": '"$ARRAY_JSON"'
                }
              }
            }
          }'
        done
