name: Upload to TestFlight

on:
  pull_request: 
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: macOS-15


    steps:
    - uses: actions/checkout@v4

    - name: Check for the existence of modified files
      env: 
        APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
        APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        APPSTORE_KEY_CONTENT: ${{ secrets.APPSTORE_KEY_CONTENT }}
      run: |
        bundle exec fastlane beta