name: Upload to TestFlight

on:
  pull_request: 
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: macOS-15

    steps:
    - uses: actions/checkout@v4

    - name: Create Workspace & Project
      run: |
        
        # Install mise
        curl https://mise.run | bash

        # Add mise to PATH (for GitHub Actions environment)
        eval "$(mise activate bash)"

        # Install Tuist and use the latest version
        mise install tuist
        mise use tuist@latest

        # Use tuist command
        tuist --version

        # Generate Tuist project
        tuist generate

    - name: Upload to TestFlight
      env: 
        APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
        APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        APPSTORE_KEY_CONTENT: ${{ secrets.APPSTORE_KEY_CONTENT }}
      run: |
        bundle exec fastlane beta