name: Upload to TestFlight

on:
  pull_request: 
    types:
      - opened

jobs:
  build:
    runs-on: macOS-15

    steps:
    - uses: actions/checkout@v4

    - name: Create Workspace & Project
      run: |
        curl -fsSL https://raw.githubusercontent.com/tuist/mise/main/install.sh | bash
        echo 'export PATH="$HOME/.mise/bin:$PATH"' >> $GITHUB_ENV
        mise install tuist
        mise use tuist@latest
        tuist generate

    - name: Upload to TestFlight
      env: 
        APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
        APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        APPSTORE_KEY_CONTENT: ${{ secrets.APPSTORE_KEY_CONTENT }}
      run: |
        bundle exec fastlane beta