name: Upload to TestFlight

on:
  pull_request: 
    types:
      - opened

jobs:
  build:
    runs-on: macOS-15

    steps:
    - uses: actions/checkout@v4

    - name: Install Tuist
      run: |
        curl -Ls https://install.tuist.io | bash
        echo 'export PATH="$HOME/.tuist/bin:$PATH"' >> $GITHUB_ENV

    - name: Generate Tuist project
      run: tuist generate

    - name: Upload to TestFlight
      env: 
        APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
        APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        APPSTORE_KEY_CONTENT: ${{ secrets.APPSTORE_KEY_CONTENT }}
      run: |
        bundle exec fastlane beta